=== garitma/aura-design-system/apps/website/public/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
      "style": {
        "type": "string",
        "enum": [
          "default"
        ]
      },
      "tailwind": {
        "type": "object",
        "properties": {
          "config": {
            "type": "string"
          },
          "css": {
            "type": "string"
          },
          "baseColor": {
            "type": "string"
          },
          "cssVariables": {
            "type": "boolean"
          },
          "prefix": {
            "type": "string"
          }
        },
        "required": [
          "config",
          "css",
          "cssVariables"
        ]
      },
      "rsc": {
        "type": "boolean"
      },
      "tsx": {
        "type": "boolean"
      },
      "iconLibrary": {
        "type": "string"
      },
      "aliases": {
        "type": "object",
        "properties": {
          "utils": {
            "type": "string"
          },
          "components": {
            "type": "string"
          },
          "ui": {
            "type": "string"
          },
          "lib": {
            "type": "string"
          },
          "hooks": {
            "type": "string"
          },
          "slices":{
            "type": "string"
          },
          "css": {
            "type": "string"
          }
        },
        "required": [
          "utils",
          "components"
        ]
      }
    },
    "required": [
      "style",
      "tailwind",
      "rsc",
      "aliases"
    ]
  }

=== garitma/aura-design-system/apps/website/public/components.json
{
  "$schema": "https://auradesignsystem.com/schema.json",
  "style": "default",
  "rsc": true,
  "tsx": true,
  "tailwind": {
    "config": "",
    "css": "app/globals.css",
    "baseColor": "default",
    "cssVariables": true
  },
  "aliases": {
    "components": "@/components",
    "utils": "@/utils/",
    "ui": "@/components/ui",
    "lib": "@/utils",
    "hooks": "@/hooks"
  },
  "iconLibrary": "radix-icons"
}

=== garitma/aura-design-system/apps/website/components.json
{
  "$schema": "https://ui.shadcn.com/schema.json",
  "style": "default",
  "rsc": true,
  "tsx": true,
  "tailwind": {
    "config": "",
    "css": "app/globals.css",
    "baseColor": "neutral",
    "cssVariables": true,
    "prefix": ""
  },
  "aliases": {
    "components": "@/components",
    "utils": "@/utils",
    "ui": "@/components/ui",
    "lib": "@/lib",
    "hooks": "@/hooks"
  },
  "iconLibrary": "lucide"
}
